name: Deploy to Heroku

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Dockerfile
        run: find . -name "Dockerfile"

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f Bootcamp/ReportHub.API/Dockerfile ]; then echo "❌ Dockerfile not found!"; exit 1; fi
          echo "✅ Dockerfile found at Bootcamp/ReportHub.API/"

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: HRKU-cf874a65-aee6-4857-8763-e992aceb791c
        run: heroku container:login

      - name: Build the Docker image
        run: |
            docker build -t registry.heroku.com/bootcamp-report-hub/web -f Bootcamp/ReportHub.API/Dockerfile Bootcamp/

      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/bootcamp-report-hub/web

      - name: Release the container
        run: |
          heroku container:release web -a bootcamp-report-hub
